<a href="https://colab.research.google.com/github/raina1234-a/Reddit-Post-Analysis-and-Moderation-Classifier/blob/main/reddit_postClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/r_dataisbeautiful_posts.csv")

/tmp/ipykernel_2019/3835883297.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/r_dataisbeautiful_posts.csv")

In [3]:
df.columns

Index(['id', 'title', 'score', 'author', 'author_flair_text', 'removed_by',
       'total_awards_received', 'awarders', 'created_utc', 'full_link',
       'num_comments', 'over_18'],
      dtype='object')

In [4]:
df.shape

(193091, 12)

In [5]:
df.describe()

               score  total_awards_received   created_utc   num_comments
count  193091.000000           53239.000000  1.930910e+05  193091.000000
mean      180.261157               0.005898  1.501766e+09      26.374502
std      1946.307188               0.241624  6.569719e+07     206.886930
min         0.000000               0.000000  1.329263e+09       0.000000
25%         1.000000               0.000000  1.449986e+09       1.000000
50%         1.000000               0.000000  1.502211e+09       1.000000
75%         4.000000               0.000000  1.561930e+09       4.000000
max    116226.000000              30.000000  1.600174e+09   18801.000000

In [6]:
df.isna().sum()

id                            0
title                         1
score                         0
author                        0
author_flair_text        166218
removed_by               177406
total_awards_received    139852
awarders                 150523
created_utc                   0
full_link                     0
num_comments                  0
over_18                       0
dtype: int64

In [7]:
df.dropna(subset=['title'],inplace=True)

In [8]:
df.drop(["author_flair_text","created_utc","awarders"],axis=1,inplace=True)

In [9]:
df.removed_by.value_counts()

removed_by
moderator           11036
deleted              2398
automod_filtered     1187
reddit               1063
author                  1
Name: count, dtype: int64

In [10]:
df.removed_by.notnull().sum()

np.int64(15685)

In [11]:
df.over_18.value_counts()

over_18
False    192093
True        997
Name: count, dtype: int64

In [12]:
df.total_awards_received.fillna(0,inplace=True)

/tmp/ipykernel_2019/976138776.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.total_awards_received.fillna(0,inplace=True)

In [13]:
df.fillna("NOT DELETED",inplace=True)

In [14]:
df

,id,title,score,author,removed_by,total_awards_received,full_link,num_comments,over_18
0,it7yz2,[OC] The World’s Forests Mapped,1,vividmaps,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
1,it7uig,[OC] Airbnb presence mapped in Barcelona (BCN)...,1,JonnieNeptune,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
2,it7t4z,A marketplace for open streaming data sources,1,DangerMouse289,automod_filtered,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
3,it7jfq,[OC] Black Owner-Occupied Housing,1,SocialExplorerInc,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
4,it7a3r,[OC] My monthly average steps in 2020. Quarant...,1,ahmedgelemli,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
...,...,...,...,...,...,...,...,...,...
193086,pqbdl,Infosthetics seems like it belongs here.,15,magiclamp,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193087,pqav2,Time lapse of every nuclear detonation from 19...,9,th3sousa,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193088,pq922,Wavii.,13,ddshroom,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
193089,ppx09,An interactive representation of Pres. Obamas ...,21,zanycaswell,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193090,ppvl7,A map showing the geographical distribution of...,45,zanycaswell,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,5,False

In [15]:
df.groupby("author").sum()["total_awards_received"].sort_values(ascending=False)

author
PieChartPirate       30.0
Spooderman89         27.0
asherfergusson       18.0
_The_Mattmatician    14.0
Janman14             12.0
                     ...
Spickbug              0.0
SpiceEyes             0.0
SphinxP               0.0
Spheros               0.0
Spider1132            0.0
Name: total_awards_received, Length: 82566, dtype: float64

In [16]:
df["num_comments"] = pd.to_numeric(df["num_comments"], errors="coerce")
df.groupby("author")["num_comments"].sum().sort_values(ascending=False)

author
[deleted]             137201
rhiever                69063
BoMcCready             58685
jimrosenz              50146
theimpossiblesalad     49865
                       ...
raufanmingcit              0
ratytedi                   0
rattleio                   0
ratnakarnandangi           0
-Andrew1-                  0
Name: num_comments, Length: 82566, dtype: int64

In [17]:
df["score"] = pd.to_numeric(df["score"], errors="coerce")
df.groupby("author").sum()["score"].sort_values(ascending=False)

author
[deleted]         573563
neilrkaye         450520
datashown         444349
chartr            433525
Geographist       384489
                   ...
thejestercrown         0
thelolrus              0
Molteniron             0
Adolfrian              0
thename226             0
Name: score, Length: 82566, dtype: int64

In [18]:
df["over_18"] = pd.to_numeric(df["over_18"], errors="coerce")
df.groupby("author").sum()["over_18"].sort_values(ascending=False)

author
[deleted]         187
indianescorts0      7
angelrumio          5
FrigidShadow        5
licensecrack        5
                 ...
SquareBottle        0
Squageheimer        0
SqojoSmiley         0
SqlJason            0
Squarerigjack       0
Name: over_18, Length: 82566, dtype: int64

In [19]:
df.groupby(["over_18","removed_by"]).count()

                              id   title   score  author  \
over_18 removed_by
False   NOT DELETED       176498  176498  176498  176498
        author                 1       1       1       1
        automod_filtered    1181    1181    1181    1181
        deleted             2385    2385    2385    2385
        moderator          10977   10977   10977   10977
        reddit              1051    1051    1051    1051
True    NOT DELETED          907     907     907     907
        automod_filtered       6       6       6       6
        deleted               13      13      13      13
        moderator             59      59      59      59
        reddit                12      12      12      12

                          total_awards_received  full_link  num_comments
over_18 removed_by
False   NOT DELETED                      176498     176498        176498
        author                                1          1             1
        automod_filtered                   1181       1181          1181
        deleted                            2385       2385          2385
        moderator                         10977      10977         10977
        reddit                             1051       1051          1051
True    NOT DELETED                         907        907           907
        automod_filtered                      6          6             6
        deleted                              13         13            13
        moderator                            59         59            59
        reddit                               12         12            12

In [20]:
df.corr(numeric_only=True)

                          score  total_awards_received  num_comments   over_18
score                  1.000000               0.156223      0.597279  0.018457
total_awards_received  0.156223               1.000000      0.168735  0.005340
num_comments           0.597279               0.168735      1.000000  0.028543
over_18                0.018457               0.005340      0.028543  1.000000

In [21]:
df["adult_18"] = 0
df["adult_18"] = df["over_18"].apply(lambda row: 0 if row==False else 1)

In [ ]:
df["adult_18"].value_counts()

adult_18
0    70588
1      412
Name: count, dtype: int64

In [22]:
df["adult_18"] = 0
df.loc[df["removed_by"] != "NOT DELETED", "adult_18"] = 1

df["adult_18"].value_counts()

adult_18
0    177405
1     15685
Name: count, dtype: int64

In [23]:
import nltk
nltk.download("stopwords")
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [24]:
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

def preprocess_text(text):
    text = text.lower()

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in string.punctuation]

    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]

    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]

    return ' '.join(stemmed_tokens)

In [25]:
df["clean_title"] = df["title"].apply(preprocess_text)

In [26]:
df["deleted"] = 0

df.loc[df["removed_by"] != "NOT DELETED", "deleted"] = 1

df["deleted"].value_counts()

deleted
0    177405
1     15685
Name: count, dtype: int64

In [27]:
df["deleted"].value_counts(normalize=True)

deleted
0    0.918768
1    0.081232
Name: proportion, dtype: float64

In [29]:
df["deleted"].value_counts(normalize=True)

deleted
0    0.918768
1    0.081232
Name: proportion, dtype: float64

In [30]:
X = df["clean_title"]
y = df["deleted"]

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf = tfidf.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

lr_model.fit(X_train_tfidf, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [34]:
y_pred_lr = lr_model.predict(X_test_tfidf)

In [35]:
y_prob_lr = lr_model.predict_proba(X_test_tfidf)[:, 1]

In [36]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr))

Accuracy: 0.8343259619866383
Precision: 0.2778912954638333
Recall: 0.6503028371055148
F1 Score: 0.38938728765031494

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.85      0.90     35481
           1       0.28      0.65      0.39      3137

    accuracy                           0.83     38618
   macro avg       0.62      0.75      0.65     38618
weighted avg       0.91      0.83      0.86     38618

In [37]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

Confusion Matrix:
[[30180  5301]
 [ 1097  2040]]

In [38]:
X_train_tfidf
X_test_tfidf
y_train
y_test

22261     0
41324     0
109734    0
104539    0
51571     0
         ..
107022    0
103778    0
52353     0
12459     1
70171     0
Name: deleted, Length: 38618, dtype: int64

In [39]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    class_weight="balanced",
    random_state=42
)

svm_model.fit(X_train_tfidf, y_train)

LinearSVC(class_weight='balanced', random_state=42)

In [40]:
y_pred_svm = svm_model.predict(X_test_tfidf)

In [41]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print("Precision:", precision_score(y_test, y_pred_svm))
print("Recall:", recall_score(y_test, y_pred_svm))
print("F1 Score:", f1_score(y_test, y_pred_svm))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Accuracy: 0.8416541509140815
Precision: 0.2760902255639098
Recall: 0.5852725533949633
F1 Score: 0.3751915806682334

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.86      0.91     35481
           1       0.28      0.59      0.38      3137

    accuracy                           0.84     38618
   macro avg       0.62      0.72      0.64     38618
weighted avg       0.90      0.84      0.87     38618


Confusion Matrix:
[[30667  4814]
 [ 1301  1836]]

In [44]:
metadata = df[
    [
        "score",
        "num_comments",
        "total_awards_received",
        "over_18"
    ]
].copy()
metadata.head()

   score  num_comments  total_awards_received  over_18
0      1             1                    0.0    False
1      1             0                    0.0    False
2      1             0                    0.0    False
3      1             1                    0.0    False
4      1             0                    0.0    False

In [45]:
metadata["score"] = pd.to_numeric(
    metadata["score"],
    errors="coerce"
)

metadata["num_comments"] = pd.to_numeric(
    metadata["num_comments"],
    errors="coerce"
)

metadata["total_awards_received"] = pd.to_numeric(
    metadata["total_awards_received"],
    errors="coerce"
)

metadata["over_18"] = pd.to_numeric(
    metadata["over_18"],
    errors="coerce"
)

In [46]:
metadata.isnull().sum()

score                    0
num_comments             0
total_awards_received    0
over_18                  0
dtype: int64

In [47]:
X_meta_train = metadata.loc[X_train.index]
X_meta_test = metadata.loc[X_test.index]

print(X_meta_train.shape)
print(X_meta_test.shape)

(154472, 4)
(38618, 4)

In [48]:
from xgboost import XGBClassifier
scale_pos_weight = (
    (y_train == 0).sum() /
    (y_train == 1).sum()
)

print("Scale Pos Weight:", scale_pos_weight)

Scale Pos Weight: 11.310487727127828

In [50]:
xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_meta_train,
    y_train
)

y_pred_xgb = xgb_model.predict(X_meta_test)

y_prob_xgb = xgb_model.predict_proba(X_meta_test)[:, 1]

In [51]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

Accuracy: 0.7377647729038272
Precision: 0.19907008782503874
Recall: 0.7370098820529168
F1 Score: 0.3134702732018168

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.74      0.84     35481
           1       0.20      0.74      0.31      3137

    accuracy                           0.74     38618
   macro avg       0.58      0.74      0.58     38618
weighted avg       0.91      0.74      0.80     38618


Confusion Matrix:
[[26179  9302]
 [  825  2312]]