<a href="https://colab.research.google.com/github/raina1234-a/Reddit-Post-Analysis-and-Moderation-Classifier/blob/main/reddit_postClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("/content/r_dataisbeautiful_posts.csv")

/tmp/ipykernel_60515/3835883297.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/r_dataisbeautiful_posts.csv")

In [32]:
df

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
0,it7yz2,[OC] The World’s Forests Mapped,1,vividmaps,NaN,NaN,0.0,[],1600173678,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
1,it7uig,[OC] Airbnb presence mapped in Barcelona (BCN)...,1,JonnieNeptune,OC: 2,NaN,0.0,[],1600173208,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
2,it7t4z,A marketplace for open streaming data sources,1,DangerMouse289,NaN,automod_filtered,0.0,[],1600173075,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
3,it7jfq,[OC] Black Owner-Occupied Housing,1,SocialExplorerInc,OC: 17,NaN,0.0,[],1600172010,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
4,it7a3r,[OC] My monthly average steps in 2020. Quarant...,1,ahmedgelemli,OC: 2,NaN,0.0,[],1600171002,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
193086,pqbdl,Infosthetics seems like it belongs here.,15,magiclamp,NaN,NaN,NaN,NaN,1329282849,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193087,pqav2,Time lapse of every nuclear detonation from 19...,9,th3sousa,NaN,NaN,NaN,NaN,1329282160,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193088,pq922,Wavii.,13,ddshroom,NaN,NaN,NaN,NaN,1329279777,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
193089,ppx09,An interactive representation of Pres. Obamas ...,21,zanycaswell,NaN,NaN,NaN,NaN,1329265203,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193090,ppvl7,A map showing the geographical distribution of...,45,zanycaswell,NaN,NaN,NaN,NaN,1329263456,https://www.reddit.com/r/dataisbeautiful/comme...,5,False

In [33]:
df.columns

Index(['id', 'title', 'score', 'author', 'author_flair_text', 'removed_by',
       'total_awards_received', 'awarders', 'created_utc', 'full_link',
       'num_comments', 'over_18'],
      dtype='object')

In [34]:
df.shape

(193091, 12)

In [35]:
df.describe()

               score  total_awards_received   created_utc   num_comments
count  193091.000000           53239.000000  1.930910e+05  193091.000000
mean      180.261157               0.005898  1.501766e+09      26.374502
std      1946.307188               0.241624  6.569719e+07     206.886930
min         0.000000               0.000000  1.329263e+09       0.000000
25%         1.000000               0.000000  1.449986e+09       1.000000
50%         1.000000               0.000000  1.502211e+09       1.000000
75%         4.000000               0.000000  1.561930e+09       4.000000
max    116226.000000              30.000000  1.600174e+09   18801.000000

In [36]:
df.isna().sum()

id                            0
title                         1
score                         0
author                        0
author_flair_text        166218
removed_by               177406
total_awards_received    139852
awarders                 150523
created_utc                   0
full_link                     0
num_comments                  0
over_18                       0
dtype: int64

In [37]:
df.dropna(subset=['title'],inplace=True)

In [38]:
df.drop(["author_flair_text","created_utc","awarders"],axis=1,inplace=True)

In [39]:
df.removed_by.value_counts()

removed_by
moderator           11036
deleted              2398
automod_filtered     1187
reddit               1063
author                  1
Name: count, dtype: int64

In [40]:
df.removed_by.notnull().sum()

np.int64(15685)

In [41]:
df.over_18.value_counts()

over_18
False    192093
True        997
Name: count, dtype: int64

In [42]:
df.total_awards_received.fillna(0,inplace=True)

/tmp/ipykernel_60515/976138776.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.total_awards_received.fillna(0,inplace=True)

In [43]:
df.isna().sum()

id                            0
title                         0
score                         0
author                        0
removed_by               177405
total_awards_received         0
full_link                     0
num_comments                  0
over_18                       0
dtype: int64

In [44]:
df.fillna("NOT DELETED",inplace=True)

In [45]:
df.isna().sum()

id                       0
title                    0
score                    0
author                   0
removed_by               0
total_awards_received    0
full_link                0
num_comments             0
over_18                  0
dtype: int64

In [46]:
df

,id,title,score,author,removed_by,total_awards_received,full_link,num_comments,over_18
0,it7yz2,[OC] The World’s Forests Mapped,1,vividmaps,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
1,it7uig,[OC] Airbnb presence mapped in Barcelona (BCN)...,1,JonnieNeptune,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
2,it7t4z,A marketplace for open streaming data sources,1,DangerMouse289,automod_filtered,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
3,it7jfq,[OC] Black Owner-Occupied Housing,1,SocialExplorerInc,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1,False
4,it7a3r,[OC] My monthly average steps in 2020. Quarant...,1,ahmedgelemli,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
...,...,...,...,...,...,...,...,...,...
193086,pqbdl,Infosthetics seems like it belongs here.,15,magiclamp,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193087,pqav2,Time lapse of every nuclear detonation from 19...,9,th3sousa,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193088,pq922,Wavii.,13,ddshroom,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,2,False
193089,ppx09,An interactive representation of Pres. Obamas ...,21,zanycaswell,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0,False
193090,ppvl7,A map showing the geographical distribution of...,45,zanycaswell,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,5,False

In [47]:
df.groupby("author").sum()["total_awards_received"].sort_values(ascending=False)

author
PieChartPirate       30.0
Spooderman89         27.0
asherfergusson       18.0
_The_Mattmatician    14.0
Janman14             12.0
                     ...
Spickbug              0.0
SpiceEyes             0.0
SphinxP               0.0
Spheros               0.0
Spider1132            0.0
Name: total_awards_received, Length: 82566, dtype: float64

In [48]:
df.groupby("author").sum()["num_comments"].sort_values(ascending=False)

author
[deleted]             137201
rhiever                69063
BoMcCready             58685
jimrosenz              50146
theimpossiblesalad     49865
                       ...
raufanmingcit              0
ratytedi                   0
rattleio                   0
ratnakarnandangi           0
-Andrew1-                  0
Name: num_comments, Length: 82566, dtype: int64

In [49]:
df.groupby("author").sum()["score"].sort_values(ascending=False)

author
[deleted]         573563
neilrkaye         450520
datashown         444349
chartr            433525
Geographist       384489
                   ...
thejestercrown         0
thelolrus              0
Molteniron             0
Adolfrian              0
thename226             0
Name: score, Length: 82566, dtype: int64

In [50]:
df.groupby("author").sum()["over_18"].sort_values(ascending=False)

author
[deleted]         187
indianescorts0      7
angelrumio          5
FrigidShadow        5
licensecrack        5
                 ...
SquareBottle        0
Squageheimer        0
SqojoSmiley         0
SqlJason            0
Squarerigjack       0
Name: over_18, Length: 82566, dtype: int64

In [51]:
df.groupby(["over_18","removed_by"]).count()

                              id   title   score  author  \
over_18 removed_by
False   NOT DELETED       176498  176498  176498  176498
        author                 1       1       1       1
        automod_filtered    1181    1181    1181    1181
        deleted             2385    2385    2385    2385
        moderator          10977   10977   10977   10977
        reddit              1051    1051    1051    1051
True    NOT DELETED          907     907     907     907
        automod_filtered       6       6       6       6
        deleted               13      13      13      13
        moderator             59      59      59      59
        reddit                12      12      12      12

                          total_awards_received  full_link  num_comments
over_18 removed_by
False   NOT DELETED                      176498     176498        176498
        author                                1          1             1
        automod_filtered                   1181       1181          1181
        deleted                            2385       2385          2385
        moderator                         10977      10977         10977
        reddit                             1051       1051          1051
True    NOT DELETED                         907        907           907
        automod_filtered                      6          6             6
        deleted                              13         13            13
        moderator                            59         59            59
        reddit                               12         12            12

In [53]:
df.corr(numeric_only=True)

                          score  total_awards_received  num_comments   over_18
score                  1.000000               0.156223      0.597279  0.018457
total_awards_received  0.156223               1.000000      0.168735  0.005340
num_comments           0.597279               0.168735      1.000000  0.028543
over_18                0.018457               0.005340      0.028543  1.000000